export namespace strings {
    namespace en {
        let quickCheck: string;
        let questionNumber: string;
        let unknown: string;
        let ruleRightGain: string;
        let ruleRightLoss: string;
        let ruleRightZero: string;
        let ruleWrongGain: string;
        let ruleWrongLoss: string;
        let ruleWrongZero: string;
        let ruleUnknownGain: string;
        let ruleUnknownLoss: string;
        let ruleUnknownZero: string;
        let pointOne: string;
        let pointSingular: string;
        let pointPlural: string;
        let check: string;
        let unansweredOne: string;
        let unanswered: string;
        let choose: string;
        let summary: string;
        let countRightOne: string;
        let countRightMany: string;
        let countWrongOne: string;
        let countWrongMany: string;
        let countUnknownOne: string;
        let countUnknownMany: string;
        let markCorrect: string;
        let markWrong: string;
        let markAnswer: string;
        let markUnknown: string;
        let review: string;
        let answers: string;
        let correct: string;
        let restart: string;
        let cleared: string;
    }
    namespace fr {
        let quickCheck_1: string;
        export { quickCheck_1 as quickCheck };
        let questionNumber_1: string;
        export { questionNumber_1 as questionNumber };
        let unknown_1: string;
        export { unknown_1 as unknown };
        let ruleRightGain_1: string;
        export { ruleRightGain_1 as ruleRightGain };
        let ruleRightLoss_1: string;
        export { ruleRightLoss_1 as ruleRightLoss };
        let ruleRightZero_1: string;
        export { ruleRightZero_1 as ruleRightZero };
        let ruleWrongGain_1: string;
        export { ruleWrongGain_1 as ruleWrongGain };
        let ruleWrongLoss_1: string;
        export { ruleWrongLoss_1 as ruleWrongLoss };
        let ruleWrongZero_1: string;
        export { ruleWrongZero_1 as ruleWrongZero };
        let ruleUnknownGain_1: string;
        export { ruleUnknownGain_1 as ruleUnknownGain };
        let ruleUnknownLoss_1: string;
        export { ruleUnknownLoss_1 as ruleUnknownLoss };
        let ruleUnknownZero_1: string;
        export { ruleUnknownZero_1 as ruleUnknownZero };
        let pointOne_1: string;
        export { pointOne_1 as pointOne };
        let pointSingular_1: string;
        export { pointSingular_1 as pointSingular };
        let pointPlural_1: string;
        export { pointPlural_1 as pointPlural };
        let check_1: string;
        export { check_1 as check };
        let unansweredOne_1: string;
        export { unansweredOne_1 as unansweredOne };
        let unanswered_1: string;
        export { unanswered_1 as unanswered };
        let choose_1: string;
        export { choose_1 as choose };
        let summary_1: string;
        export { summary_1 as summary };
        let countRightOne_1: string;
        export { countRightOne_1 as countRightOne };
        let countRightMany_1: string;
        export { countRightMany_1 as countRightMany };
        let countWrongOne_1: string;
        export { countWrongOne_1 as countWrongOne };
        let countWrongMany_1: string;
        export { countWrongMany_1 as countWrongMany };
        let countUnknownOne_1: string;
        export { countUnknownOne_1 as countUnknownOne };
        let countUnknownMany_1: string;
        export { countUnknownMany_1 as countUnknownMany };
        let markCorrect_1: string;
        export { markCorrect_1 as markCorrect };
        let markWrong_1: string;
        export { markWrong_1 as markWrong };
        let markAnswer_1: string;
        export { markAnswer_1 as markAnswer };
        let markUnknown_1: string;
        export { markUnknown_1 as markUnknown };
        let review_1: string;
        export { review_1 as review };
        let answers_1: string;
        export { answers_1 as answers };
        let correct_1: string;
        export { correct_1 as correct };
        let restart_1: string;
        export { restart_1 as restart };
        let cleared_1: string;
        export { cleared_1 as cleared };
    }
}
export type Strings = typeof strings.en;
