export const strings = {
  en: {
    answer: 'Write your answer first.',
    check: 'Check my answer', emptyAnswer: 'Write your answer first.',
    hadIt: 'Did you have it?', yes: 'Yes', notQuite: 'Not quite', noted: 'Noted.',
    write: 'Write {count} wrong options and the misconception behind each.',
    writeOne: 'Write one wrong option and the misconception behind it.',
    two: 'two', three: 'three', four: 'four', five: 'five',
    yourQuestion: 'Your question', authorQuestion: "The author's question", correctAnswer: 'Correct answer',
    rightAnswer: 'Right answer',
    option: 'Wrong option {key}', misconception: 'Which misconception does it target?',
    chooseOne: 'Choose one', other: 'Something else', custom: 'Describe the misconception',
    compare: "Compare with the author's",
    targets: 'Targets: {target}', match: 'Same misconception as the author',
    empty: 'Write wrong option {n}.', longText: 'Keep option {n} to {max} characters or fewer.',
    right: 'Option {n} is the right answer. Write a wrong one.', duplicate: 'Make option {n} different from your earlier options.',
    choose: 'Choose what option {n} targets.', describe: 'Describe the misconception for option {n}.',
    longCustom: 'Keep the misconception for option {n} to {max} characters or fewer.',
    errorsOne: '1 field needs attention.', errorsMany: '{count} fields need attention.',
    coverageOne: "You targeted {authorTargeted} of the author's {authorTotal} misconception, and {ownExtra} of your own.",
    coverageMany: "You targeted {authorTargeted} of the author's {authorTotal} misconceptions, and {ownExtra} of your own.",
    clear: 'Start over', cleared: 'Answer and options cleared.'
  },
  fr: {
    answer: "Rédigez d'abord votre réponse.",
    check: 'Vérifier ma réponse', emptyAnswer: "Écrivez d'abord votre réponse.",
    hadIt: 'Aviez-vous la bonne réponse?', yes: 'Oui', notQuite: 'Pas tout à fait', noted: 'Noté.',
    write: "Rédigez {count} mauvaises réponses et l'idée fausse derrière chacune.",
    writeOne: "Rédigez une mauvaise réponse et l'idée fausse derrière celle-ci.",
    two: 'deux', three: 'trois', four: 'quatre', five: 'cinq',
    yourQuestion: 'Votre question', authorQuestion: "La question de l'auteur", correctAnswer: 'Bonne réponse',
    rightAnswer: 'Bonne réponse',
    option: 'Mauvaise réponse {key}', misconception: 'Quelle idée fausse cible-t-elle?',
    chooseOne: 'Choisissez une idée fausse', other: 'Autre idée fausse', custom: 'Décrivez l\'idée fausse',
    compare: 'Comparer avec les réponses de l\'auteur',
    targets: 'Cible : {target}', match: "Même idée fausse que l'auteur",
    empty: 'Rédigez la mauvaise réponse {n}.', longText: 'Limitez la réponse {n} à {max} caractères.',
    right: 'La réponse {n} est la bonne réponse. Rédigez-en une mauvaise.', duplicate: 'La réponse {n} doit être différente de vos réponses précédentes.',
    choose: 'Choisissez ce que la réponse {n} cible.', describe: 'Décrivez l\'idée fausse pour la réponse {n}.',
    longCustom: 'Limitez l\'idée fausse de la réponse {n} à {max} caractères.',
    errorsOne: '1 champ demande votre attention.', errorsMany: '{count} champs demandent votre attention.',
    coverageOne: 'Vous avez ciblé {authorTargeted} sur {authorTotal} idée fausse de l\'auteur, et {ownExtra} des vôtres.',
    coverageMany: 'Vous avez ciblé {authorTargeted} sur {authorTotal} idées fausses de l\'auteur, et {ownExtra} des vôtres.',
    clear: 'Recommencer', cleared: 'Réponses effacées.'
  }
};
/** @typedef {typeof strings.en} Strings */
