export const strings = {
  en: {
    answer: 'Write your answer first.',
    check: 'Check my answer', emptyAnswer: 'Write your answer before you check it.',
    hadIt: 'Was your answer right?', yes: 'Yes', notQuite: 'Not quite', noted: 'Noted.',
    write: 'Write {count} wrong options. Name the mistaken idea behind each.',
    writeOne: 'Write one wrong option. Name the mistaken idea behind it.',
    two: 'two', three: 'three', four: 'four', five: 'five',
    yourQuestion: 'Your question', authorQuestion: "The author's question", correctAnswer: 'Correct answer',
    rightAnswer: 'Right answer',
    option: 'Wrong option {key}', misconception: 'What mistaken idea could lead to this answer?',
    chooseOne: 'Choose one', other: 'Something else', custom: 'Describe the mistaken idea',
    compare: "Compare with the author's",
    targets: 'Mistaken idea: {target}', match: 'Same mistaken idea as the author',
    empty: 'Write wrong option {n}.', longText: 'Keep option {n} to {max} characters or fewer.',
    right: 'Option {n} is the right answer. Write a wrong one.', duplicate: 'Make option {n} different from your earlier options.',
    choose: 'Choose the mistaken idea behind option {n}.', describe: 'Describe the mistaken idea for option {n}.',
    longCustom: 'Keep the mistaken idea for option {n} to {max} characters or fewer.',
    errorsOne: '1 field needs attention.', errorsMany: '{count} fields need attention.',
    coverageOne: "Your labels match {authorTargeted} of the author's {authorTotal} mistaken idea. You added {ownExtra} of your own.",
    coverageMany: "Your labels match {authorTargeted} of the author's {authorTotal} mistaken ideas. You added {ownExtra} of your own.",
    clear: 'Start over', cleared: 'Answer and options cleared.'
  },
  fr: {
    answer: "Rédigez d'abord votre réponse.",
    check: 'Vérifier ma réponse', emptyAnswer: 'Écrivez votre réponse avant de la vérifier.',
    hadIt: 'Votre réponse était-elle bonne ?', yes: 'Oui', notQuite: 'Pas tout à fait', noted: 'Noté.',
    write: "Rédigez {count} mauvaises réponses. Nommez l'idée fausse derrière chacune.",
    writeOne: "Rédigez une mauvaise réponse. Nommez l'idée fausse derrière celle-ci.",
    two: 'deux', three: 'trois', four: 'quatre', five: 'cinq',
    yourQuestion: 'Votre question', authorQuestion: "La question de l'auteur", correctAnswer: 'Bonne réponse',
    rightAnswer: 'Bonne réponse',
    option: 'Mauvaise réponse {key}', misconception: 'Quelle idée fausse pourrait mener à cette réponse ?',
    chooseOne: 'Choisissez une idée fausse', other: 'Autre idée fausse', custom: 'Décrivez l\'idée fausse',
    compare: 'Comparer avec les réponses de l\'auteur',
    targets: 'Idée fausse : {target}', match: "Même idée fausse que l'auteur",
    empty: 'Rédigez la mauvaise réponse {n}.', longText: 'Limitez la réponse {n} à {max} caractères.',
    right: 'La réponse {n} est la bonne réponse. Rédigez-en une mauvaise.', duplicate: 'La réponse {n} doit être différente de vos réponses précédentes.',
    choose: 'Choisissez l\'idée fausse derrière la réponse {n}.', describe: 'Décrivez l\'idée fausse pour la réponse {n}.',
    longCustom: 'Limitez l\'idée fausse de la réponse {n} à {max} caractères.',
    errorsOne: '1 champ demande votre attention.', errorsMany: '{count} champs demandent votre attention.',
    coverageOne: 'Idée fausse en commun avec l\'auteur : {authorTargeted} sur {authorTotal}. Autres idées fausses : {ownExtra}.',
    coverageMany: 'Idées fausses en commun avec l\'auteur : {authorTargeted} sur {authorTotal}. Autres idées fausses : {ownExtra}.',
    clear: 'Recommencer', cleared: 'Réponses effacées.'
  }
};
/** @typedef {typeof strings.en} Strings */
