export const strings = {
  en: {
    placeholder: 'Enter your question here…',
    checking: 'Looking…',
    noMatch: 'No answer yet',
    add: 'Add to the question bank',
    bank: 'Question bank',
    bankNotice: 'These example answers show how a question bank could work. Your questions stay in this tab until you close it.',
    waiting: 'Waiting for an answer',
    instructor: 'Instructor',
    learner: 'Another learner',
    remove: 'Remove question',
    removeQuestion: 'Remove question {number}',
    showAll: 'Show all',
    showLatest: 'Show latest 10',
    added: 'Question added to your bank.',
    removed: 'Question removed from your bank.',
    saved: 'This question is in your bank.',
    storageError: 'Your browser could not save the change. Try again.',
    bankFull: 'Your bank is full. Remove a question to add another.',
    paused: 'Press Enter to look up another question.',
    fallback: 'Lookup is unavailable. Browse the list below.',
    faqList: 'All questions and answers',
    sectionList: 'Course outline',
    found: 'Answer found: {title}',
    sectionFound: 'Section found: {title}'
  },
  fr: {
    placeholder: 'Entrez votre question ici…',
    checking: 'Recherche…',
    noMatch: 'Pas encore de réponse',
    add: 'Ajouter à la banque de questions',
    bank: 'Banque de questions',
    bankNotice: 'Ces réponses donnent un aperçu d’une banque de questions. Vos questions restent dans cet onglet jusqu’à sa fermeture.',
    waiting: 'En attente d’une réponse',
    instructor: 'Personne responsable du cours',
    learner: 'Une autre personne du cours',
    remove: 'Retirer la question',
    removeQuestion: 'Retirer la question {number}',
    showAll: 'Tout afficher',
    showLatest: 'Afficher les 10 dernières',
    added: 'Question ajoutée à votre banque.',
    removed: 'Question retirée de votre banque.',
    saved: 'Cette question est dans votre banque.',
    storageError: 'Votre navigateur n’a pas pu enregistrer le changement. Réessayez.',
    bankFull: 'Votre banque est pleine. Retirez une question pour en ajouter une autre.',
    paused: 'Appuyez sur Entrée pour chercher une autre question.',
    fallback: 'La recherche est indisponible. Consultez la liste ci-dessous.',
    faqList: 'Toutes les questions et réponses',
    sectionList: 'Plan du cours',
    found: 'Réponse trouvée : {title}',
    sectionFound: 'Section trouvée : {title}'
  }
};
/** @typedef {typeof strings.en} Strings */
