export namespace strings {
    namespace en {
        let to: string;
        let subject: string;
        let answer: string;
        let check: string;
        let empty: string;
        let tick: string;
        let meter: string;
        let show: string;
        let resultAll: string;
        let resultOne: string;
        let resultMany: string;
        let mine: string;
        let model: string;
        let legend: string;
        let included: string;
        let notIncluded: string;
        let whole: string;
        let restart: string;
        let cleared: string;
        let checkOwn: string;
        let summary: string;
    }
    namespace fr {
        let to_1: string;
        export { to_1 as to };
        let subject_1: string;
        export { subject_1 as subject };
        let answer_1: string;
        export { answer_1 as answer };
        let check_1: string;
        export { check_1 as check };
        let empty_1: string;
        export { empty_1 as empty };
        let tick_1: string;
        export { tick_1 as tick };
        let meter_1: string;
        export { meter_1 as meter };
        let show_1: string;
        export { show_1 as show };
        let resultAll_1: string;
        export { resultAll_1 as resultAll };
        let resultOne_1: string;
        export { resultOne_1 as resultOne };
        let resultMany_1: string;
        export { resultMany_1 as resultMany };
        let mine_1: string;
        export { mine_1 as mine };
        let model_1: string;
        export { model_1 as model };
        let legend_1: string;
        export { legend_1 as legend };
        let included_1: string;
        export { included_1 as included };
        let notIncluded_1: string;
        export { notIncluded_1 as notIncluded };
        let whole_1: string;
        export { whole_1 as whole };
        let restart_1: string;
        export { restart_1 as restart };
        let cleared_1: string;
        export { cleared_1 as cleared };
        let checkOwn_1: string;
        export { checkOwn_1 as checkOwn };
        let summary_1: string;
        export { summary_1 as summary };
    }
}
export type Strings = typeof strings.en;
