export namespace strings {
    namespace en {
        let run: string;
        let running: string;
        let samples: string;
        let language: string;
        let english: string;
        let french: string;
        let author: string;
        let model: string;
        let met: string;
        let missed: string;
        let unsure: string;
        let agree: string;
        let disagree: string;
        let notRun: string;
        let failed: string;
        let review: string;
        let answer: string;
        let cellsNote: string;
        let cell: string;
        let allAgree: string;
        let summary: string;
        let disagreement: string;
        let disagreements: string;
        let uncertainty: string;
        let uncertainties: string;
        let unrun: string;
        let progress: string;
        let saved: string;
        let live: string;
        let ready: string;
        let unavailable: string;
        let partial: string;
    }
    namespace fr {
        let run_1: string;
        export { run_1 as run };
        let running_1: string;
        export { running_1 as running };
        let samples_1: string;
        export { samples_1 as samples };
        let language_1: string;
        export { language_1 as language };
        let english_1: string;
        export { english_1 as english };
        let french_1: string;
        export { french_1 as french };
        let author_1: string;
        export { author_1 as author };
        let model_1: string;
        export { model_1 as model };
        let met_1: string;
        export { met_1 as met };
        let missed_1: string;
        export { missed_1 as missed };
        let unsure_1: string;
        export { unsure_1 as unsure };
        let agree_1: string;
        export { agree_1 as agree };
        let disagree_1: string;
        export { disagree_1 as disagree };
        let notRun_1: string;
        export { notRun_1 as notRun };
        let failed_1: string;
        export { failed_1 as failed };
        let review_1: string;
        export { review_1 as review };
        let answer_1: string;
        export { answer_1 as answer };
        let cellsNote_1: string;
        export { cellsNote_1 as cellsNote };
        let cell_1: string;
        export { cell_1 as cell };
        let allAgree_1: string;
        export { allAgree_1 as allAgree };
        let summary_1: string;
        export { summary_1 as summary };
        let disagreement_1: string;
        export { disagreement_1 as disagreement };
        let disagreements_1: string;
        export { disagreements_1 as disagreements };
        let uncertainty_1: string;
        export { uncertainty_1 as uncertainty };
        let uncertainties_1: string;
        export { uncertainties_1 as uncertainties };
        let unrun_1: string;
        export { unrun_1 as unrun };
        let progress_1: string;
        export { progress_1 as progress };
        let saved_1: string;
        export { saved_1 as saved };
        let live_1: string;
        export { live_1 as live };
        let ready_1: string;
        export { ready_1 as ready };
        let unavailable_1: string;
        export { unavailable_1 as unavailable };
        let partial_1: string;
        export { partial_1 as partial };
    }
}
export type Strings = typeof strings.en;
