export const strings = {
  en: {
    questionNumber: 'Question {number} of {total}',
    unknown: "I don't know",
    ruleRightGain: 'A right answer scores {points}.',
    ruleRightLoss: 'A right answer costs {points}.',
    ruleRightZero: 'A right answer scores no points.',
    ruleWrongGain: 'A wrong answer scores {points}.',
    ruleWrongLoss: 'A wrong answer costs {points}.',
    ruleWrongZero: 'A wrong answer costs nothing.',
    ruleUnknownGain: '"I don\'t know" scores {points}.',
    ruleUnknownLoss: '"I don\'t know" costs {points}.',
    ruleUnknownZero: '"I don\'t know" costs nothing.',
    pointOne: 'a point',
    pointSingular: '{count} point',
    pointPlural: '{count} points',
    check: 'Check my answers',
    unansweredOne: "1 question needs an answer. Choose an answer or \"I don't know\".",
    unanswered: "{count} questions need answers. Choose an answer or \"I don't know\".",
    choose: 'Choose an answer',
    summary: 'Score {points} out of {total}.',
    countRightOne: '{count} right',
    countRightMany: '{count} right',
    countWrongOne: '{count} wrong',
    countWrongMany: '{count} wrong',
    countUnknownOne: '{count} "I don\'t know"',
    countUnknownMany: '{count} "I don\'t know"',
    markCorrect: 'Correct',
    markWrong: 'Not quite',
    markAnswer: 'Correct answer',
    markUnknown: "You chose \"I don't know\"",
    review: 'Review',
    answers: 'Answers',
    correct: 'Correct answer: {option}.',
    restart: 'Start over',
    cleared: 'Answers cleared.'
  },
  fr: {
    questionNumber: 'Question {number} sur {total}',
    unknown: 'Je ne sais pas',
    ruleRightGain: 'Une bonne réponse rapporte {points}.',
    ruleRightLoss: 'Une bonne réponse coûte {points}.',
    ruleRightZero: 'Une bonne réponse ne rapporte aucun point.',
    ruleWrongGain: 'Une mauvaise réponse rapporte {points}.',
    ruleWrongLoss: 'Une mauvaise réponse coûte {points}.',
    ruleWrongZero: 'Une mauvaise réponse ne coûte rien.',
    ruleUnknownGain: '« Je ne sais pas » rapporte {points}.',
    ruleUnknownLoss: '« Je ne sais pas » coûte {points}.',
    ruleUnknownZero: '« Je ne sais pas » ne coûte rien.',
    pointOne: 'un point',
    pointSingular: '{count} point',
    pointPlural: '{count} points',
    check: 'Vérifier mes réponses',
    unansweredOne: 'Répondez à la question restante ou choisissez « Je ne sais pas ».',
    unanswered: 'Répondez aux {count} questions restantes ou choisissez « Je ne sais pas ».',
    choose: 'Choisissez une réponse',
    summary: 'Score de {points} sur {total}.',
    countRightOne: '{count} bonne réponse',
    countRightMany: '{count} bonnes réponses',
    countWrongOne: '{count} mauvaise réponse',
    countWrongMany: '{count} mauvaises réponses',
    countUnknownOne: '{count} « Je ne sais pas »',
    countUnknownMany: '{count} « Je ne sais pas »',
    markCorrect: 'Correct',
    markWrong: 'Pas tout à fait',
    markAnswer: 'Bonne réponse',
    markUnknown: 'Vous avez choisi « Je ne sais pas »',
    review: 'À revoir',
    answers: 'Réponses',
    correct: 'Bonne réponse : {option}.',
    restart: 'Recommencer',
    cleared: 'Réponses effacées.'
  }
};
/** @typedef {typeof strings.en} Strings */
