export namespace strings {
    namespace en {
        let placement: string;
        let outline: string;
        let question: string;
        let instructions: string;
        let start: string;
        let back: string;
        let next: string;
        let review: string;
        let section: string;
        let buildsOn: string;
        let todo: string;
        let passed: string;
        let credited: string;
        let creditFrom: string;
        let check: string;
        let choose: string;
        let unansweredOne: string;
        let unanswered: string;
        let summary: string;
        let summaryOne: string;
        let markCorrect: string;
        let markWrong: string;
        let markAnswer: string;
        let policy: string;
        let required: string;
        let answers: string;
        let correct: string;
        let restart: string;
        let cleared: string;
    }
    namespace fr {
        let placement_1: string;
        export { placement_1 as placement };
        let outline_1: string;
        export { outline_1 as outline };
        let question_1: string;
        export { question_1 as question };
        let instructions_1: string;
        export { instructions_1 as instructions };
        let start_1: string;
        export { start_1 as start };
        let back_1: string;
        export { back_1 as back };
        let next_1: string;
        export { next_1 as next };
        let review_1: string;
        export { review_1 as review };
        let section_1: string;
        export { section_1 as section };
        let buildsOn_1: string;
        export { buildsOn_1 as buildsOn };
        let todo_1: string;
        export { todo_1 as todo };
        let passed_1: string;
        export { passed_1 as passed };
        let credited_1: string;
        export { credited_1 as credited };
        let creditFrom_1: string;
        export { creditFrom_1 as creditFrom };
        let check_1: string;
        export { check_1 as check };
        let choose_1: string;
        export { choose_1 as choose };
        let unansweredOne_1: string;
        export { unansweredOne_1 as unansweredOne };
        let unanswered_1: string;
        export { unanswered_1 as unanswered };
        let summary_1: string;
        export { summary_1 as summary };
        let summaryOne_1: string;
        export { summaryOne_1 as summaryOne };
        let markCorrect_1: string;
        export { markCorrect_1 as markCorrect };
        let markWrong_1: string;
        export { markWrong_1 as markWrong };
        let markAnswer_1: string;
        export { markAnswer_1 as markAnswer };
        let policy_1: string;
        export { policy_1 as policy };
        let required_1: string;
        export { required_1 as required };
        let answers_1: string;
        export { answers_1 as answers };
        let correct_1: string;
        export { correct_1 as correct };
        let restart_1: string;
        export { restart_1 as restart };
        let cleared_1: string;
        export { cleared_1 as cleared };
    }
}
export type Strings = typeof strings.en;
