export namespace strings {
    namespace en {
        let formats: string;
        let text: string;
        let slides: string;
        let audio: string;
        let outline: string;
        let quiz: string;
        let place: string;
        let showing: string;
        let previous: string;
        let next: string;
        let play: string;
        let playUnavailable: string;
        let sample: string;
        let scriptNote: string;
        let noQuestion: string;
        let check: string;
        let choose: string;
        let correct: string;
        let wrong: string;
        let quizSummary: string;
        let summary: string;
    }
    namespace fr {
        let formats_1: string;
        export { formats_1 as formats };
        let text_1: string;
        export { text_1 as text };
        let slides_1: string;
        export { slides_1 as slides };
        let audio_1: string;
        export { audio_1 as audio };
        let outline_1: string;
        export { outline_1 as outline };
        let quiz_1: string;
        export { quiz_1 as quiz };
        let place_1: string;
        export { place_1 as place };
        let showing_1: string;
        export { showing_1 as showing };
        let previous_1: string;
        export { previous_1 as previous };
        let next_1: string;
        export { next_1 as next };
        let play_1: string;
        export { play_1 as play };
        let playUnavailable_1: string;
        export { playUnavailable_1 as playUnavailable };
        let sample_1: string;
        export { sample_1 as sample };
        let scriptNote_1: string;
        export { scriptNote_1 as scriptNote };
        let noQuestion_1: string;
        export { noQuestion_1 as noQuestion };
        let check_1: string;
        export { check_1 as check };
        let choose_1: string;
        export { choose_1 as choose };
        let correct_1: string;
        export { correct_1 as correct };
        let wrong_1: string;
        export { wrong_1 as wrong };
        let quizSummary_1: string;
        export { quizSummary_1 as quizSummary };
        let summary_1: string;
        export { summary_1 as summary };
    }
}
export type Strings = typeof strings.en;
