export namespace strings {
    namespace en {
        let journal: string;
        let start: string;
        let firstLabel: string;
        let saveFirst: string;
        let saved: string;
        let kept: string;
        let firstSaved: string;
        let courseNote: string;
        let skip: string;
        let end: string;
        let nowLabel: string;
        let compare: string;
        let tick: string;
        let compared: string;
        let missing: string;
        let tryAgain: string;
        let restart: string;
        let cleared: string;
        let noScript: string;
        let empty: string;
        let tooLong: string;
        let unreadable: string;
        let writeFailed: string;
        let summary: string;
    }
    namespace fr {
        let journal_1: string;
        export { journal_1 as journal };
        let start_1: string;
        export { start_1 as start };
        let firstLabel_1: string;
        export { firstLabel_1 as firstLabel };
        let saveFirst_1: string;
        export { saveFirst_1 as saveFirst };
        let saved_1: string;
        export { saved_1 as saved };
        let kept_1: string;
        export { kept_1 as kept };
        let firstSaved_1: string;
        export { firstSaved_1 as firstSaved };
        let courseNote_1: string;
        export { courseNote_1 as courseNote };
        let skip_1: string;
        export { skip_1 as skip };
        let end_1: string;
        export { end_1 as end };
        let nowLabel_1: string;
        export { nowLabel_1 as nowLabel };
        let compare_1: string;
        export { compare_1 as compare };
        let tick_1: string;
        export { tick_1 as tick };
        let compared_1: string;
        export { compared_1 as compared };
        let missing_1: string;
        export { missing_1 as missing };
        let tryAgain_1: string;
        export { tryAgain_1 as tryAgain };
        let restart_1: string;
        export { restart_1 as restart };
        let cleared_1: string;
        export { cleared_1 as cleared };
        let noScript_1: string;
        export { noScript_1 as noScript };
        let empty_1: string;
        export { empty_1 as empty };
        let tooLong_1: string;
        export { tooLong_1 as tooLong };
        let unreadable_1: string;
        export { unreadable_1 as unreadable };
        let writeFailed_1: string;
        export { writeFailed_1 as writeFailed };
        let summary_1: string;
        export { summary_1 as summary };
    }
}
export type Strings = typeof strings.en;
