export const strings = {
  "en": {
    "to": "To",
    "subject": "Subject",
    "answer": "Your message",
    "check": "Check my answer",
    "empty": "Write your message first.",
    "tick": "Select each part you can point to in your message.",
    "meter": "{count} of {total}",
    "show": "Show feedback",
    "resultAll": "Compare your wording with the model.",
    "resultOne": "One part to add: {label}.",
    "resultMany": "Compare the marked parts with your message.",
    "mine": "Your message",
    "model": "Model answer",
    "legend": "The parts",
    "included": "Included",
    "notIncluded": "To add",
    "whole": "Across the whole message",
    "restart": "Start over",
    "cleared": "Cleared.",
    "checkOwn": "Check your message for these parts.",
    "summary": "You included {count} of {total} parts."
  },
  "fr": {
    "to": "À",
    "subject": "Objet",
    "answer": "Votre message",
    "check": "Vérifier ma réponse",
    "empty": "Écrivez d'abord votre message.",
    "tick": "Sélectionnez chaque élément que vous trouvez dans votre message.",
    "meter": "{count} sur {total}",
    "show": "Afficher la rétroaction",
    "resultAll": "Comparez votre formulation avec le modèle.",
    "resultOne": "Un élément à ajouter : {label}.",
    "resultMany": "Comparez les éléments marqués avec votre message.",
    "mine": "Votre message",
    "model": "Réponse modèle",
    "legend": "Les éléments",
    "included": "Inclus",
    "notIncluded": "À ajouter",
    "whole": "Dans l'ensemble du message",
    "restart": "Recommencer",
    "cleared": "Réponse effacée.",
    "checkOwn": "Vérifiez si votre message contient ces éléments.",
    "summary": "Éléments inclus : {count} sur {total}."
  }
};
/** @typedef {typeof strings.en} Strings */
