export const strings = {
  "en": {
    "scenario": "Your task",
    "to": "To",
    "subject": "Subject",
    "answer": "Your message",
    "check": "Check my answer",
    "empty": "Write your message first.",
    "tick": "Which parts did you include?",
    "tickHelp": "Read your message again. Select each part you can point to.",
    "meter": "{count} of {total}",
    "show": "Show feedback",
    "resultAll": "Every part is there. Compare your wording with the model.",
    "resultOne": "One part to add: {label}.",
    "resultMany": "{n} parts to add. Each one is marked in the model answer.",
    "mine": "Your message",
    "model": "Model answer",
    "legend": "The parts",
    "included": "Included",
    "notIncluded": "To add",
    "whole": "Across the whole message",
    "restart": "Start over",
    "cleared": "Cleared.",
    "checkOwn": "Check your own answer",
    "partsQuestion": "Did your message include these parts?",
    "summary": "You included {count} of {total} parts."
  },
  "fr": {
    "scenario": "Votre tâche",
    "to": "À",
    "subject": "Objet",
    "answer": "Votre message",
    "check": "Vérifier ma réponse",
    "empty": "Écrivez d'abord votre message.",
    "tick": "Quels éléments avez-vous inclus?",
    "tickHelp": "Relisez votre message. Sélectionnez chaque élément que vous y trouvez.",
    "meter": "{count} sur {total}",
    "show": "Afficher la rétroaction",
    "resultAll": "Tous les éléments y sont. Comparez votre formulation avec le modèle.",
    "resultOne": "Un élément à ajouter : {label}.",
    "resultMany": "{n} éléments à ajouter. Chacun est marqué dans la réponse modèle.",
    "mine": "Votre message",
    "model": "Réponse modèle",
    "legend": "Les éléments",
    "included": "Inclus",
    "notIncluded": "À ajouter",
    "whole": "Dans l'ensemble du message",
    "restart": "Recommencer",
    "cleared": "Réponse effacée.",
    "checkOwn": "Vérifiez votre réponse",
    "partsQuestion": "Votre message comprenait-il ces éléments?",
    "summary": "Vous avez inclus {count} des {total} éléments."
  }
};
/** @typedef {typeof strings.en} Strings */
