export const strings = {
  "en": {
    "to": "To",
    "subject": "Subject",
    "answer": "Your answer",
    "check": "Check my answer",
    "empty": "Write your answer first.",
    "tick": "Tick each part your answer includes.",
    "meter": "{count} of {total}",
    "show": "Show feedback",
    "resultAll": "Compare your wording with the model answer.",
    "resultOne": "One part to add. {label}.",
    "resultMany": "Use the hints to add missing parts.",
    "mine": "Your answer",
    "model": "Model answer",
    "legend": "The parts",
    "included": "Included",
    "notIncluded": "To add",
    "whole": "Whole answer",
    "restart": "Start over",
    "cleared": "Answer cleared.",
    "checkOwn": "Check for these parts.",
    "summary": "You ticked {count} of {total} parts."
  },
  "fr": {
    "to": "À",
    "subject": "Objet",
    "answer": "Votre réponse",
    "check": "Vérifier ma réponse",
    "empty": "Écrivez d'abord votre réponse.",
    "tick": "Cochez chaque élément présent dans votre réponse.",
    "meter": "{count} sur {total}",
    "show": "Afficher la rétroaction",
    "resultAll": "Comparez votre formulation avec la réponse modèle.",
    "resultOne": "Un élément à ajouter. {label}.",
    "resultMany": "Ajoutez les éléments manquants à l'aide des conseils.",
    "mine": "Votre réponse",
    "model": "Réponse modèle",
    "legend": "Les éléments",
    "included": "Inclus",
    "notIncluded": "À ajouter",
    "whole": "Toute la réponse",
    "restart": "Recommencer",
    "cleared": "Réponse effacée.",
    "checkOwn": "Vérifiez ces éléments dans votre réponse.",
    "summary": "Éléments cochés : {count} sur {total}."
  }
};
/** @typedef {typeof strings.en} Strings */
