export namespace strings {
    namespace en {
        let answer: string;
        let check: string;
        let emptyAnswer: string;
        let hadIt: string;
        let yes: string;
        let notQuite: string;
        let noted: string;
        let write: string;
        let writeOne: string;
        let two: string;
        let three: string;
        let four: string;
        let five: string;
        let yourQuestion: string;
        let authorQuestion: string;
        let correctAnswer: string;
        let rightAnswer: string;
        let option: string;
        let misconception: string;
        let chooseOne: string;
        let other: string;
        let custom: string;
        let compare: string;
        let targets: string;
        let match: string;
        let empty: string;
        let longText: string;
        let right: string;
        let duplicate: string;
        let choose: string;
        let describe: string;
        let longCustom: string;
        let errorsOne: string;
        let errorsMany: string;
        let coverageOne: string;
        let coverageMany: string;
        let clear: string;
        let cleared: string;
    }
    namespace fr {
        let answer_1: string;
        export { answer_1 as answer };
        let check_1: string;
        export { check_1 as check };
        let emptyAnswer_1: string;
        export { emptyAnswer_1 as emptyAnswer };
        let hadIt_1: string;
        export { hadIt_1 as hadIt };
        let yes_1: string;
        export { yes_1 as yes };
        let notQuite_1: string;
        export { notQuite_1 as notQuite };
        let noted_1: string;
        export { noted_1 as noted };
        let write_1: string;
        export { write_1 as write };
        let writeOne_1: string;
        export { writeOne_1 as writeOne };
        let two_1: string;
        export { two_1 as two };
        let three_1: string;
        export { three_1 as three };
        let four_1: string;
        export { four_1 as four };
        let five_1: string;
        export { five_1 as five };
        let yourQuestion_1: string;
        export { yourQuestion_1 as yourQuestion };
        let authorQuestion_1: string;
        export { authorQuestion_1 as authorQuestion };
        let correctAnswer_1: string;
        export { correctAnswer_1 as correctAnswer };
        let rightAnswer_1: string;
        export { rightAnswer_1 as rightAnswer };
        let option_1: string;
        export { option_1 as option };
        let misconception_1: string;
        export { misconception_1 as misconception };
        let chooseOne_1: string;
        export { chooseOne_1 as chooseOne };
        let other_1: string;
        export { other_1 as other };
        let custom_1: string;
        export { custom_1 as custom };
        let compare_1: string;
        export { compare_1 as compare };
        let targets_1: string;
        export { targets_1 as targets };
        let match_1: string;
        export { match_1 as match };
        let empty_1: string;
        export { empty_1 as empty };
        let longText_1: string;
        export { longText_1 as longText };
        let right_1: string;
        export { right_1 as right };
        let duplicate_1: string;
        export { duplicate_1 as duplicate };
        let choose_1: string;
        export { choose_1 as choose };
        let describe_1: string;
        export { describe_1 as describe };
        let longCustom_1: string;
        export { longCustom_1 as longCustom };
        let errorsOne_1: string;
        export { errorsOne_1 as errorsOne };
        let errorsMany_1: string;
        export { errorsMany_1 as errorsMany };
        let coverageOne_1: string;
        export { coverageOne_1 as coverageOne };
        let coverageMany_1: string;
        export { coverageMany_1 as coverageMany };
        let clear_1: string;
        export { clear_1 as clear };
        let cleared_1: string;
        export { cleared_1 as cleared };
    }
}
export type Strings = typeof strings.en;
