export namespace strings {
    namespace en {
        let question: string;
        let rightAnswer: string;
        let instruction: string;
        let option: string;
        let text: string;
        let misconception: string;
        let chooseOne: string;
        let other: string;
        let custom: string;
        let compare: string;
        let author: string;
        let yours: string;
        let targets: string;
        let match: string;
        let noMatch: string;
        let empty: string;
        let longText: string;
        let right: string;
        let duplicate: string;
        let choose: string;
        let describe: string;
        let longCustom: string;
        let errorsOne: string;
        let errorsMany: string;
        let targeted: string;
        let missed: string;
        let none: string;
        let same: string;
        let extraOne: string;
        let extraTwo: string;
        let extraMany: string;
        let or: string;
        let summary: string;
        let clear: string;
        let cleared: string;
    }
    namespace fr {
        let question_1: string;
        export { question_1 as question };
        let rightAnswer_1: string;
        export { rightAnswer_1 as rightAnswer };
        let instruction_1: string;
        export { instruction_1 as instruction };
        let option_1: string;
        export { option_1 as option };
        let text_1: string;
        export { text_1 as text };
        let misconception_1: string;
        export { misconception_1 as misconception };
        let chooseOne_1: string;
        export { chooseOne_1 as chooseOne };
        let other_1: string;
        export { other_1 as other };
        let custom_1: string;
        export { custom_1 as custom };
        let compare_1: string;
        export { compare_1 as compare };
        let author_1: string;
        export { author_1 as author };
        let yours_1: string;
        export { yours_1 as yours };
        let targets_1: string;
        export { targets_1 as targets };
        let match_1: string;
        export { match_1 as match };
        let noMatch_1: string;
        export { noMatch_1 as noMatch };
        let empty_1: string;
        export { empty_1 as empty };
        let longText_1: string;
        export { longText_1 as longText };
        let right_1: string;
        export { right_1 as right };
        let duplicate_1: string;
        export { duplicate_1 as duplicate };
        let choose_1: string;
        export { choose_1 as choose };
        let describe_1: string;
        export { describe_1 as describe };
        let longCustom_1: string;
        export { longCustom_1 as longCustom };
        let errorsOne_1: string;
        export { errorsOne_1 as errorsOne };
        let errorsMany_1: string;
        export { errorsMany_1 as errorsMany };
        let targeted_1: string;
        export { targeted_1 as targeted };
        let missed_1: string;
        export { missed_1 as missed };
        let none_1: string;
        export { none_1 as none };
        let same_1: string;
        export { same_1 as same };
        let extraOne_1: string;
        export { extraOne_1 as extraOne };
        let extraTwo_1: string;
        export { extraTwo_1 as extraTwo };
        let extraMany_1: string;
        export { extraMany_1 as extraMany };
        let or_1: string;
        export { or_1 as or };
        let summary_1: string;
        export { summary_1 as summary };
        let clear_1: string;
        export { clear_1 as clear };
        let cleared_1: string;
        export { cleared_1 as cleared };
    }
}
export type Strings = typeof strings.en;
