export const strings = {
  en: {
    instruction: 'On your chosen date, answer from memory. Then check the back.',
    dateLabel: 'Test myself on',
    spacingLegend: 'When will you test yourself?',
    in2Days: 'In 2 days',
    in1Week: 'In 1 week',
    in2Weeks: 'In 2 weeks',
    in1Month: 'In 1 month',
    anotherDate: 'Another date',
    customDateLabel: 'Date',
    dateError: 'Choose a valid date.',
    dateChanged: 'Test yourself on {date}.',
    sides: 'Sheet side',
    front: 'Front',
    back: 'Back',
    questions: 'Questions',
    answers: 'Answers',
    backInstruction: 'Check your answers. Review what you missed.',
    print: 'Print the sheet',
    printHint: 'Questions print first, then answers. For one double-sided sheet, choose the long-edge flip in your print settings.',
    printing: 'Print dialog opened.'
  },
  fr: {
    instruction: "À la date choisie, répondez de mémoire. Vérifiez ensuite au verso.",
    dateLabel: 'Me tester le',
    spacingLegend: 'Quand voulez-vous vous tester ?',
    in2Days: 'Dans 2 jours',
    in1Week: 'Dans 1 semaine',
    in2Weeks: 'Dans 2 semaines',
    in1Month: 'Dans 1 mois',
    anotherDate: 'Une autre date',
    customDateLabel: 'Date',
    dateError: 'Choisissez une date valide.',
    dateChanged: 'Testez vos connaissances le {date}.',
    sides: 'Côté de la feuille',
    front: 'Recto',
    back: 'Verso',
    questions: 'Questions',
    answers: 'Réponses',
    backInstruction: 'Vérifiez vos réponses. Revoyez ce que vous avez manqué.',
    print: 'Imprimer la feuille',
    printHint: "Les questions s'impriment avant les réponses. Pour une feuille recto verso, choisissez le retournement sur le bord long dans les réglages d'impression.",
    printing: "La boîte de dialogue d'impression est ouverte."
  }
};
/** @typedef {typeof strings.en} Strings */
