export const strings = {
  en: {
    placement: 'Placement check',
    outline: 'Course outline',
    questions: 'What do you already know?',
    instructions: 'Answer each question. Passing a section also credits the sections it builds on.',
    section: 'Section {number}: {title}',
    buildsOn: 'Builds on: {sections}.',
    todo: 'To do',
    passed: 'Passed, you can skip it',
    credited: 'Credited from {section}',
    check: 'Check my answers',
    choose: 'Choose an answer',
    unansweredOne: '1 question unanswered. Choose an answer for each.',
    unanswered: '{count} questions unanswered. Choose an answer for each.',
    summary: 'You can skip {skip} of {total} sections.',
    summaryOne: 'You can skip {skip} of {total} sections.',
    markCorrect: 'Correct',
    markWrong: 'Not quite',
    markAnswer: 'Correct answer',
    policy: 'Some clients need proof that every section was seen. The author can turn off test-out.',
    required: 'The author requires every section. This check will not let you skip any.',
    answers: 'Answers',
    correct: 'Correct answer: {option}.',
    restart: 'Start over',
    cleared: 'Cleared.'
  },
  fr: {
    placement: 'Vérification des acquis',
    outline: 'Plan du cours',
    questions: 'Que savez-vous déjà?',
    instructions: 'Répondez à chaque question. Réussir une section vous donne aussi le crédit pour les sections sur lesquelles elle repose.',
    section: 'Section {number} : {title}',
    buildsOn: 'Repose sur : {sections}.',
    todo: 'À faire',
    passed: 'Réussie, vous pouvez la passer',
    credited: 'Créditée grâce à {section}',
    check: 'Vérifier mes réponses',
    choose: 'Choisissez une réponse',
    unansweredOne: '1 question sans réponse. Choisissez une réponse pour chacune.',
    unanswered: '{count} questions sans réponse. Choisissez une réponse pour chacune.',
    summary: 'Vous pouvez passer {skip} sections sur {total}.',
    summaryOne: 'Vous pouvez passer {skip} section sur {total}.',
    markCorrect: 'Correct',
    markWrong: 'Pas tout à fait',
    markAnswer: 'Bonne réponse',
    policy: "Certains clients exigent une preuve que chaque section a été vue. L'auteur peut désactiver cette option.",
    required: "L'auteur exige que vous suiviez chaque section. Cette vérification ne vous permet pas d'en passer.",
    answers: 'Réponses',
    correct: 'Bonne réponse : {option}.',
    restart: 'Recommencer',
    cleared: 'Réponses effacées.'
  }
};
/** @typedef {typeof strings.en} Strings */
