export const strings = {
  en: {
    outline: "What you'll cover",
    resultOutline: 'Your course plan',
    question: 'Question {number} of {total}: {section}',
    instructions: 'Answer one question per section. If you pass, you can skip it.',
    start: 'Start the check',
    back: 'Back',
    next: 'Next',
    review: 'Review answers',
    section: 'Section {number}: {title}',
    buildsOn: 'Builds on: {sections}.',
    todo: 'Take it',
    passed: 'Skip',
    check: 'Check my answers',
    choose: 'Choose an answer',
    unansweredOne: '1 question unanswered. Choose an answer for each.',
    unanswered: '{count} questions unanswered. Choose an answer for each.',
    summary: 'You can skip {skip} of {total} sections.',
    summaryOne: 'You can skip {skip} of {total} sections.',
    markCorrect: 'Correct',
    markWrong: 'Not quite',
    markAnswer: 'Correct answer',
    policy: 'Some clients need proof that every section was seen. The author can turn off test-out.',
    required: 'The author requires every section. This check will not let you skip any.',
    answers: 'Answers',
    correct: 'Correct answer: {option}.',
    restart: 'Start over',
    cleared: 'Cleared.'
  },
  fr: {
    outline: 'Au programme',
    resultOutline: 'Votre parcours',
    question: 'Question {number} sur {total} : {section}',
    instructions: 'Répondez à une question par section. Si vous réussissez, vous pouvez la passer.',
    start: 'Commencer la vérification',
    back: 'Retour',
    next: 'Suivant',
    review: 'Revoir les réponses',
    section: 'Section {number} : {title}',
    buildsOn: 'Repose sur : {sections}.',
    todo: 'À suivre',
    passed: 'Passer',
    check: 'Vérifier mes réponses',
    choose: 'Choisissez une réponse',
    unansweredOne: '1 question sans réponse. Choisissez une réponse pour chacune.',
    unanswered: '{count} questions sans réponse. Choisissez une réponse pour chacune.',
    summary: 'Sections que vous pouvez passer : {skip} sur {total}.',
    summaryOne: 'Sections que vous pouvez passer : {skip} sur {total}.',
    markCorrect: 'Correct',
    markWrong: 'Pas tout à fait',
    markAnswer: 'Bonne réponse',
    policy: "Certains clients exigent une preuve que chaque section a été vue. L'auteur peut désactiver la possibilité de passer des sections.",
    required: "L'auteur exige que vous suiviez chaque section. Cette vérification ne vous permet pas d'en passer.",
    answers: 'Réponses',
    correct: 'Bonne réponse : {option}.',
    restart: 'Recommencer',
    cleared: 'Réponses effacées.'
  }
};
/** @typedef {typeof strings.en} Strings */
