export const strings = {
  en: {
    outline: "What you'll cover",
    resultOutline: 'Your course plan',
    question: 'Question {number} of {total}: {section}',
    instructions: 'Answer the questions to see which sections you can skip.',
    start: 'Start the check',
    back: 'Back',
    next: 'Next',
    review: 'Review answers',
    section: 'Section {number}: {title}',
    buildsOn: 'Builds on {sections}.',
    todo: 'Take it',
    passed: 'Skip',
    check: 'Check my answers',
    choose: 'Choose an answer',
    unansweredOne: 'Choose an answer for the remaining question.',
    unanswered: 'Choose an answer for each of the {count} remaining questions.',
    summary: 'You can skip {skip} of {total} sections.',
    summaryOne: 'You can skip this section.',
    summaryOneRequired: 'You need to take this section.',
    markCorrect: 'Correct',
    markWrong: 'Not quite',
    markAnswer: 'Correct answer',
    policy: 'Some courses require you to take every section.',
    required: 'You need to take every section in this course.',
    answers: 'Answers',
    correct: 'Correct answer: {option}.',
    restart: 'Start over',
    cleared: 'Cleared.'
  },
  fr: {
    outline: 'Au programme',
    resultOutline: 'Votre parcours',
    question: 'Question {number} sur {total} : {section}',
    instructions: 'Répondez aux questions pour voir quelles sections vous pouvez passer.',
    start: 'Commencer la vérification',
    back: 'Retour',
    next: 'Suivant',
    review: 'Revoir les réponses',
    section: 'Section {number} : {title}',
    buildsOn: 'Repose sur {sections}.',
    todo: 'À suivre',
    passed: 'Passer',
    check: 'Vérifier mes réponses',
    choose: 'Choisissez une réponse',
    unansweredOne: 'Choisissez une réponse à la question restante.',
    unanswered: 'Choisissez une réponse à chacune des {count} questions restantes.',
    summary: 'Sections que vous pouvez passer : {skip} sur {total}.',
    summaryOne: 'Vous pouvez passer cette section.',
    summaryOneRequired: 'Vous devez suivre cette section.',
    markCorrect: 'Correct',
    markWrong: 'Pas tout à fait',
    markAnswer: 'Bonne réponse',
    policy: "Certains cours exigent que vous suiviez chaque section.",
    required: "Vous devez suivre chaque section de ce cours.",
    answers: 'Réponses',
    correct: 'Bonne réponse : {option}.',
    restart: 'Recommencer',
    cleared: 'Réponses effacées.'
  }
};
/** @typedef {typeof strings.en} Strings */
